# slot_game_setting.yaml
# 游戏设置配置
    game_id: 1
    game_name: "DojoMeow"
    slot_type: 1    # 1-连线 2-待定 3-待定
    extra:  # 扩展设置
        test: 
          test2: "test2"
        odds: # 符号:赔率- 连线后该符号的赔率,如下是3连线的赔率,4连 10:[0,0,88,888]=3连88 4连888 
            "10": [0, 0, 100]
            "11": [0, 0, 50]
            "12": [0, 0, 10]
            "13": [0, 0, 5]
            "14": [0, 0, 3]
            "15": [0, 0, 2]
            "16": [0, 0, 200]
            "17": [0, 0, 0]
        line_data: # 连线数据 
            - [0, 0, 0]
            - [0, 1, 0]
            - [0, 1, 1]
            - [1, 1, 0]
            - [1, 1, 1]
            - [1, 2, 1]
            - [1, 2, 2]
            - [2, 2, 1]
            - [2, 2, 2]
            - [2, 3, 2]
 
