#  redis  配置
redis:
  db0:
    addr: "127.0.0.1:6379"
    password: "123456"
    db: 0
    poolSize: 20
    minIdleConns: 5
    poolTimeout: 5
  db1:
    addr: "127.0.0.1:6379"
    password: "123456"
    db: 1
    poolSize: 20
    minIdleConns: 5
    poolTimeout: 5
  db2:
    addr: "127.0.0.1:6379"
    password: "123456"
    db: 2
    poolSize: 20
    minIdleConns: 5
    poolTimeout: 5
